logging: 
  config: file:config/log4j2.xml
spring:
  application:
    name: gate-server
game:
  server :
    serverId: 1001
    port: 8809
    bossThreads: 1
    workThreads: 16
    idleTime: 300
    connectTimeout: 10
    