logging:
  config: file:config/log4j2.xml
spring:
  application:
    name: gate-server
game:
  server:
    port: 8809
    bossThreads: 1
    workThreads: 16
    idleTime: 300
    connectTimeout: 10
  rocketmq:
    instance-name: GateServer
    consumer-group-name: GateMessageConsumerGroup
    consumer-topic: GateMessageConsumerTopic
    publish-topic: GateMessageProducerTopic3
    publish-topic-key: GateMessageProduceTopicKey
    publish-topic-queue-num: 8
    name-server-addr: 127.0.0.1:9876
    publish-group-name: GateMessageProduceGrooup
eureka:
  instance:
    app-group-name: gate-server-group
    appname: gate-server-1
    instance-id: 101-1
    prefer-ip-address: true
    ip-address: 192.168.0.192
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 15
    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/