logging:
  config: file:config/log4j2.xml
spring:
  application:
    name: gate-server
game:
  server:
    port: 8809
    bossThreads: 1
    workThreads: 16
    idleTime: 300
    connectTimeout: 10
  message: 
    publish: 
      groupName: gate-server-group
      instance-name: gate-server-1
      name-server-addr: 127.0.0.1:9876
      queue-num: 3
      topic: GateMessageProduceTopic
      topic-key: GateMessageProduceTopicKey
      
    consume: 
      group-name: GateMessageConsumerGroup
      instance-name: gate-server-1
      name-server-addr: 127.0.0.1:9876
      topic: GateMessageConsumerTopic
      
eureka:
  instance:
    app-group-name: gate-server-group
    appname: gate-server-1
    instance-id: 101-1
    prefer-ip-address: true
    ip-address: 192.168.0.192
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 15
    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/