logging: 
  config: file:config/log4j2.xml
spring:
  application:
    name: gate-server
game:
  server :
    serverId: 1001
    port: 8809
    bossThreads: 1
    workThreads: 16
    idleTime: 300
    connectTimeout: 10
    serverTypeMap: 
      1001: [2001,2002]
      
  rocketmq:
    instance-name: GateServer
    consumer-group-name: GateMessageConsumerGroup
    consumer-topic: GateMessageConsumerTopic
    publish-topic: GateMessageProducerTopic3
    publish-topic-key: GateMessageProduceTopicKey
    publish-topic-queue-num: 8
    name-server-addr: 127.0.0.1:9876
    publish-group-name: GateMessageProduceGrooup
    