logging:
  config: file:config/log4j2.xml
spring:
  application:
    # 服务器实例名，格式：定义的名称字符串_服务类型_服务id
    name: game-server
game:
  server:
    server-id: 2001
    threads: 16
  message:
    consume:
      group-name: LogicServerMessageConsumerGroup
      instance-name:  LogicServer-1
      name-server-addr: 127.0.0.1:9876
      topic: GateMessageProduceTopic
    publish:
      group-name: LogicMessageProduceGrooup
      instance-name: LogicServer-1
      name-server-addr:  127.0.0.1:9876
      queue-num: 1
      topic: GateMessageConsumerTopic
      topic-key: GateMessageConsumerTopicKey
   
    
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.192
    appname: LogicServer-1
    app-group-name: LogicServer
    instance-id: 2001-1   
    
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 15
    
    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/