logging: 
  config: file:config/log4j2.xml
server: 
  port: 8181
spring:
  application:
    name: gateway_balance_a
    
gateway: 
  server: 
    config: 
      gatewayServer: 
        - serverId: 1001
          host: 192.168.1.169
          port: 8088
          
        - serverId: 1002
          host: 192.168.1.179
          port: 8089