logging:
  config: file:config/log4j2.xml
server:
  port: 8761
spring:
  application:
    name: xinyue-eureka-server-101-1
eureka:
  server:
    response-cache-update-interval-ms: 3000
    responseCacheAutoExpirationInSeconds: 3
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/